spring.application.name=extensive-reading-manager

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Entityクラスの内容を見て、自動的にDBのテーブルを作成・更新する設定
spring.jpa.hibernate.ddl-auto=update

# 発行されたSQLをコンソールに表示する（学習・デバッグ用）
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Spring AI用のGemini APIキー設定
spring.ai.google.genai.api-key=${GEMINI_API_KEY}